Update polymake_jll to use FLINT 2.7.0
JuliaPackaging/Yggdrasil pull request #2304
Opened 2020-12-23 09:46 UTC by fingolfin

Also update its version to follow our new scheme.

Should only be merged with @benlorenz approval. CC @thofma 

I've debated with myself whether to also hardcode the `normaliz_jll` version (it also depends on FLINT_jll), but right now I think this is not necessary as the usual package dependency mechanism will take care of it. Alas, Benjamin or Tommy might disagree.

2020-12-23 21:50 UTC, benlorenz requested changes
thanks, lets try if 4.3 also works.

2020-12-23 21:50 UTC, benlorenz commented on P/polymake/build_tarballs.jl
> +upstream_version = v"4.2.1"
```suggestion
version = v"400.300.000"
upstream_version = v"4.3.0"
```

2020-12-23 21:50 UTC, benlorenz commented on P/polymake/build_tarballs.jl
> +                  "d308f551ef4c9f490a3a848d45a1ab41ae6461b1daf5be3deeaebad7df3816d4")
```suggestion
                  "1f0ef1c022a214c935189b72e8ac67e6c6315bf9dff5fc87c3d704d3e76cb994")
```

2020-12-24 00:09 UTC, fingolfin commented
@benlorenz seems to build

2020-12-25 00:42 UTC, giordano commented
Good to go?

2020-12-25 10:03 UTC, benlorenz commented
Yeah good to go, I will do some tests once it is in the registry. It should not affect any existing packages due to the new version.

2020-12-25 10:08 UTC, merged