[(GNU) Make] Add Builder
JuliaPackaging/Yggdrasil pull request #2833
Opened 2021-04-14 03:30 UTC by Wimmerer

First pass. Excluded Windows. Believe there is an issue related to http://gnu-make.2324884.n4.nabble.com/REGRESSION-cross-compile-4-3-fail-on-mingw-w64-7-0-GCC-9-2-td19810.html

2021-04-14 03:34 UTC, Wimmerer commented
Ok I'll work on mingw tomorrow. Question though. Is it Make, make or gmake for the name here?

2021-04-14 03:56 UTC, Wimmerer commented
Compiling make version 4.2 I seem to only be missing `glob.h`:
```cc -DHAVE_CONFIG_H -I. -I..  -I./include -I./subproc -I..   -g -O2 -MT compat/libw32_a-posixfcn.o -MD -MP -MF compat/.deps/libw32_a-posixfcn.Tpo -c -o compat/libw32_a-posixfcn.o `test -f 'compat/posixfcn.c' || echo './'`compat/posixfcn.c
In file included from pathstuff.c:17:0:```
`../makeint.h:453:18: fatal error: glob.h: No such file or directory`
`#include <glob.h>`

`glob.h` _is_ in ./workspace/srcdir/make-4.2/glob/glob.h and ./opt/x86_64-linux-musl/x86_64-linux-musl/sys-root/usr/include/glob.h
I assume it's wanting a mingw specific glob.h?

I'll investigate if msys2 does something different here.

2021-04-14 04:01 UTC, Wimmerer commented
http://savannah.gnu.org/bugs/?48037

2021-04-16 03:33 UTC, Wimmerer commented
Not totally happy with going around the makefile. It should work with Windows, but a straight up translation of the .bat file for mingw installation was recommended for other people attempting this, and it works without other changes.

2021-04-17 00:07 UTC, giordano requested changes
Some comments already given on Slack:

* the directory should be renamed to `G/GNUMake`
* a simple Makefile for Windows would be way more straightforward, maintainable and easy to read than the current manually written commands

2021-04-17 00:07 UTC, giordano commented on M/GNUMake/bundled/patches/make-4.3_undef-HAVE_STRUCT_DIRENT_D_TYPE.patch
> + /* Define to 1 if you have the `isatty' function. */
```suggestion
 /* Define to 1 if you have the `isatty' function. */

```

2021-04-18 17:02 UTC, giordano commented on G/GNUMake/bundled/Makefile
> +	cc $(CPPFLAGS) $(CFLAGS) -o $(bindir)/make$(exeext)  -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -lodbc32 -lodbccp32 $^ -Wl,--out-implib=$(prefix
I just realised with probably don't need to pass `CPPFLAGS` to link `make.exe`, let's try:
```suggestion
	cc $(CFLAGS) -o $(bindir)/make$(exeext)  -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -luuid -lodbc32 -lodbccp32 $^ -Wl,--out-implib=$(prefix)/lib/libgnumake-1.dll.a
```

2021-04-18 17:15 UTC, giordano approved these changes

2021-04-18 17:15 UTC, merged