[rtmidi] init. was it because i made the pr from codespaces?
JuliaPackaging/Yggdrasil pull request #3604
Opened 2021-09-10 05:18 UTC by anandijain

2021-09-10 05:23 UTC, anandijain commented
evidently it was because of codespaces

2021-09-10 23:18 UTC, staticfloat commented
Okay I built a new version of ALSA_jll; we'll wait for that to trickle through, then try again.

2021-09-13 05:17 UTC, wookay requested changes

2021-09-13 05:17 UTC, wookay commented on R/rtmidi/build_tarballs.jl
> +version = v"5.0.0"
I think that it should be `v"4.0.0"` .  https://github.com/thestk/rtmidi/blob/6e4e763/RtMidi.h#L61

2021-09-13 17:57 UTC, anandijain commented
what do I do about the platforms that failed?

2021-09-13 19:11 UTC, merged