Unpin Mbed TLS from version 2.24
JuliaPackaging/Yggdrasil pull request #4180
Opened 2022-01-06 08:23 UTC by mkitti

Currently Mbed TLS is pinned to 2.24, including in some julia dependencies:

1. [LibSSH2](https://github.com/JuliaPackaging/Yggdrasil/blob/f81c3d85a7c911c796cefa08091210d1810cac80/L/LibSSH2/build_tarballs.jl#L45
)
2. [LibGit2](https://github.com/JuliaPackaging/Yggdrasil/blob/f81c3d85a7c911c796cefa08091210d1810cac80/L/LibGit2/build_tarballs.jl#L62)
3. [Curl](https://github.com/JuliaPackaging/Yggdrasil/blob/f81c3d85a7c911c796cefa08091210d1810cac80/L/LibCURL/build_tarballs.jl#L79)

This creates an issue when trying to update Mbed TLS in Julia: https://github.com/JuliaLang/julia/pull/42311

We need to remove the pin, which should be possible with Julia 1.6.

This should allow Mbed TLS to be upgraded to 2.27 or 2.28 in response to security advisories.

Note that GDAL and NetCDF use a configure function that I'm not familiar with. Perhaps these need a Julia 1.6 compat declaration.

2022-01-06 09:18 UTC, giordano requested changes
I'm not sure what's your point, but mbedtls regularly breaks ABI, fixing the compat bounds is _necessary_

2022-01-06 09:23 UTC, giordano commented
And mbedtls 2.28 in #4179 broke again the ABI, libmbedtls has soversion 14, 2.27 had 13

2022-01-06 09:23 UTC, closed without merging

2022-01-07 11:22 UTC, nalimilan commented
Why do they keep breaking the API so often?! They versioning scheme seems... original. :-/

2022-01-07 11:29 UTC, mkitti commented
@nalimilan , apparently they did not like the order of the fields:
https://github.com/ARMmbed/mbedtls/releases/tag/v2.28.0

> Some fields of mbedtls_ssl_session and mbedtls_ssl_config are in a
different order. This only affects applications that define such
structures directly or serialize them.

2022-01-07 11:34 UTC, jeremiahpslewis commented
@mkitti @nalimilan Anyone have a rough guess as to how hard it will be to go to v3.1? Kind of wonder whether 2.28 is a porous fix, given that they promise ["Removal of many insecure or obsolete features"](https://github.com/ARMmbed/mbedtls/blob/development/docs/3.0-migration-guide.md). On the other hand, v3.0 was [affected by the same CVEs as 2.2x](https://tls.mbed.org/security)

2022-01-07 19:07 UTC, mkitti commented
In conda-forge, we currently have Julia 1.7.1 that was built with Mbed TLS 3.1, so it builds:

```
julia                     1.7.1                h989b2f6_1    conda-forge
mbedtls                   3.1.0                h9c3ff4c_0    conda-forge
```

There is likely an issue with a good portion of Yggdrasil based on the reverse depends. It's possible though.