[SDL] Bump versions
JuliaPackaging/Yggdrasil pull request #4300
Opened 2022-01-22 04:31 UTC by Gnimuc

- SDL2: 2.0.12 => 2.0.20
- SDL2_ttf: 2.0.15 => 2.0.18

Also switch from ArchiveSource to GitSource.

2022-01-22 05:09 UTC, Gnimuc commented
Looks like the build scripts for SDL_xxx are not trivial to be fixed. I don't have time to dive into the details, so waiting for others to pick this up.

2022-01-22 18:12 UTC, giordano commented
Not sure switching to Git sources was a good idea, now Windows builds fail with
```
[05:06:38] configure: error: 
[05:06:38] *** When building from a git clone you should configure and build in a
[05:06:38]     separate directory so you don't clobber SDL_config.h, SDL_revision.h
```

2022-01-22 18:43 UTC, giordano commented
And SDL2_image is successful if using the release tarball.

2022-01-22 19:01 UTC, giordano commented
And also for SDL2_mixer using the release tarball gets us past the bootstrap failure.  However during the build I get a different issue:
```
[18:58:15] grep: /workspace/destdir/lib/libogg.la: No such file or directory
[18:58:15] sed: /workspace/destdir/lib/libogg.la: No such file or directory
[18:58:15] libtool: link: `/workspace/destdir/lib/libogg.la' is not a valid libtool archive
[18:58:15] make: *** [Makefile:65: build/libSDL2_mixer.la] Error 1
```
@fingolfin we're getting again this issue, again with libogg.

2022-01-22 19:08 UTC, giordano commented
Side note: having a single PR which builds multiple package isn't a good idea either.  It makes working through warnings/errors rather cumbersome

2022-01-22 19:46 UTC, giordano commented
Another side effect of having a single PR building multiple packages is that now SDL2 works fine (after switching back to the release tarball instead of the git source) but we can't merge it.

I guess there is enough evidence that using the git source was a bad idea.

2022-01-22 19:47 UTC, giordano requested changes

2022-01-22 19:47 UTC, giordano commented on S/SDL2_ttf/build_tarballs.jl
> +    GitSource("https://github.com/libsdl-org/SDL_ttf.git", "3e702ed9bf400b0a72534f144b8bec46ee0416cb"),
You should got back to the release tarball also here, and refresh the patches

2022-01-22 19:47 UTC, giordano commented on S/SDL2_ttf/build_tarballs.jl
>  version = v"2.0.16" # <-- this version number is a lie to build for Julia v1.6
Note that this line must be removed

2022-01-22 19:47 UTC, giordano commented on S/SDL2_ttf/build_tarballs.jl
> +cd $WORKSPACE/srcdir/SDL*/
```suggestion
cd $WORKSPACE/srcdir/SDL2_ttf-*/
```

2022-01-22 21:54 UTC, fingolfin commented
> And also for SDL2_mixer using the release tarball gets us past the bootstrap failure. However during the build I get a different issue:
> 
> ```
> [18:58:15] grep: /workspace/destdir/lib/libogg.la: No such file or directory
> [18:58:15] sed: /workspace/destdir/lib/libogg.la: No such file or directory
> [18:58:15] libtool: link: `/workspace/destdir/lib/libogg.la' is not a valid libtool archive
> [18:58:15] make: *** [Makefile:65: build/libSDL2_mixer.la] Error 1
> ```
> 
> @fingolfin we're getting again this issue, again with libogg.

There is no direct reference to libogg in `SDL2_mixer`, so it must be indirect. And indeed, mpg123 references libogg.la in its artifacts, and was last rebuilt November 2019. I'll submit an update for it now.

2022-01-22 22:01 UTC, fingolfin commented on S/SDL2_ttf/build_tarballs.jl
> +cd $WORKSPACE/srcdir/SDL*/
Maybe
```suggestion
cd $WORKSPACE/srcdir/SDL2_ttf*/
```
so it'll work with both git clones and release tarballs.

2022-01-23 01:40 UTC, giordano commented
After #4307, #4308, and #4309 now also SDL2_mixer is working.  Thanks Max for the tip.

Yet another issue with bundling multiple packages in a single PR is that SDL2_* packages depend on SDL2 for the new platforms (aarch64-apple-darwin and armv6l).  So we can't possible merge this PR as is.

2022-01-23 04:55 UTC, Gnimuc commented
Thanks for all the help! I opened another PR #4310 to update SDL2.

2022-01-23 12:54 UTC, giordano commented
SDL2_mixer is good to go, but once again, being together with other packages which are failing makes it impossible to merge it alone.  There are failures for macOS in SDL2_image and you still need to refresh the patches for SDL2_ttf.  I don't think I'm going to do anything more here.

2022-01-23 13:56 UTC, Gnimuc commented
I can successfully build SDL2_image's lastest git main branch for x86_64-apple-darwin14 using its CMake build. But it looks like the M1 support is still in progress(https://github.com/libsdl-org/SDL_image/issues/182#issuecomment-909488050). I think we can try this again when new versions are released in the upstream. At this moment, I only need to update SDL2 to fix https://github.com/JuliaMultimedia/SimpleDirectMediaLayer.jl/issues/60.

2022-01-23 13:56 UTC, closed without merging