Add mrfDepth, fix #7224
JuliaPackaging/Yggdrasil pull request #7231
Opened 2023-08-21 02:14 UTC by mkitti

Add the Fortran code from R package mrfDepth, cc: @jbytecode

2023-08-21 08:56 UTC, aviks commented on M/mrfDepth/build_tarballs.jl
> +install_license ${WORKSPACE}/srcdir/mrfDepth/DESCRIPTION
License parsing tools will choke on this file. Might be better to do something like `install_license /usr/share/licenses/GPL-2.0+` ? With a comment linking to the description file?

2023-08-21 09:39 UTC, imciner2 requested changes

2023-08-21 09:39 UTC, imciner2 commented on M/mrfDepth/build_tarballs.jl
> +gfortran -shared -fPIC *.f -o libmrfDepth.${dlext}
```suggestion
$FC -shared -fPIC *.f -o libmrfDepth.${dlext}
```

Don't hardcode the compiler.

2023-08-22 00:51 UTC, mkitti commented
Preview at https://github.com/mkitti/mrfDepth_jll.jl

2023-08-22 02:26 UTC, mkitti commented
I believe all issues have been addressed here.

2023-08-22 18:26 UTC, merged