[Leptonica] Bump to 1.83.1
JuliaPackaging/Yggdrasil pull request #7443
Opened 2023-09-27 19:26 UTC by jeremiahpslewis

2023-09-27 21:49 UTC, giordano requested changes

2023-09-27 21:49 UTC, giordano commented on L/Leptonica/build_tarballs.jl
>      Dependency("Libtiff_jll"; compat="4.3.0"),
Use newer libtiff?

2023-09-27 21:49 UTC, giordano commented on L/Leptonica/build_tarballs.jl
> +    Dependency("libwebp_jll"; compat="^1.2.4"),
`^` is the default anyway 
```suggestion
    Dependency("libwebp_jll"; compat="1.2.4"),
```

2023-09-27 21:49 UTC, giordano commented on L/Leptonica/build_tarballs.jl
>      Dependency("OpenJpeg_jll"; compat="~2.4.0"),
Use newer openjpeg?

2023-09-27 21:49 UTC, giordano commented on L/Leptonica/build_tarballs.jl
> +    LibraryProduct("libleptonica", :liblept),
The change of the soname will actively break dependents.  It'd be good to fix compat bounds of dependents jll before moving forward with this PR.

2023-09-28 06:37 UTC, jeremiahpslewis commented on L/Leptonica/build_tarballs.jl
>      Dependency("Libtiff_jll"; compat="4.3.0"),
```suggestion
    Dependency("Libtiff_jll"; compat="4.5.1"),
```

2023-09-29 19:23 UTC, jeremiahpslewis commented on L/Leptonica/build_tarballs.jl
> +    Dependency("Libtiff_jll"; compat="4.5.1"),
```suggestion
    Dependency("Libtiff_jll"; compat="~4.5.1"),
```

2023-10-01 23:52 UTC, giordano approved these changes

2023-10-01 23:53 UTC, merged