edfplusdcnv
JuliaPackaging/Yggdrasil pull request #7557
Opened 2023-10-20 16:42 UTC by palday

Riffing off pandoc as a template for grabbing a project-supplied blob.

https://www.teuniz.net/edfplusd-converter/index.html

2023-10-20 23:38 UTC, giordano commented on E/edfplusdcnv/build_tarballs.jl
> +mkdir -p "${bindir}"
```suggestion
```

2023-10-20 23:38 UTC, giordano commented on E/edfplusdcnv/build_tarballs.jl
> +cp edfplusdcnv_*/* "${bindir}"
The path of the file you want to install is clearly wrong, but I'm away from computer, I don't know what's inside and can't check myself. In the meantime, suggesting a better way to install file (still with the wrong path, so it won't work anyway):
```suggestion
install -Dvm 755 edfplusdcnv_*/edfplusdcnv "${bindir}/edfplusdcnv"
```

2023-10-20 23:38 UTC, giordano commented on E/edfplusdcnv/build_tarballs.jl
> +chmod +x ${bindir}/edfplusdcnv
```suggestion
```

2023-10-22 17:19 UTC, giordano commented on E/edfplusdcnv/build_tarballs.jl
> +    ArchiveSource("https://www.teuniz.net/edfplusd-converter/edfplusdcnv_100.tar.gz", "eeb6033a2f21dc052852e3dd779da7d368f65d88e45b7e40fa14f4bb514e62b9"; unpack_target = "x86_64-linux-gnu"),
With `unpack_target = "x86_64-linux-gnu"` you're saying "call the directory `x86_64-linux-gnu`", so you either don't do this or in the build script below you install the file `${target}/edfplusdcnv`:
```suggestion
    ArchiveSource("https://www.teuniz.net/edfplusd-converter/edfplusdcnv_100.tar.gz", "eeb6033a2f21dc052852e3dd779da7d368f65d88e45b7e40fa14f4bb514e62b9"),
```

2023-10-22 17:23 UTC, giordano requested changes
As far as I can tell, the binary you're trying to redistribute has no license at all, which means we aren't allowed to redistribute it.

2023-11-14 04:31 UTC, palday commented
There is a GPL distribution of the entire source of this program's "ecosystem" (this is just a util function in a larger piece of software) but I can't figure out how to build this binary from that source. I've worked out a stopgap for my needs and probably won't get around to addressing the license/build issue, so I'm closing for now.

Thanks for the guidance and review though! :heart:

2023-11-14 04:31 UTC, closed without merging