Upgrade CoinUtils -- 2.11.10
JuliaPackaging/Yggdrasil pull request #8067
Opened 2024-02-05 06:14 UTC by amontoison

@odow

2024-02-05 08:27 UTC, odow requested changes
Wait for resolution of https://github.com/JuliaPackaging/Yggdrasil/pull/8066#discussion_r1477815422

2024-02-09 00:34 UTC, odow approved these changes
Okay try this now

2024-02-09 00:36 UTC, odow commented
A list of the order is:

[CoinUtils_jll]
[Osi_jll] 
[Clp_jll] 
[Cgl_jll] 
[Cbc_jll] 
[Bonmin_jll] 
[SYMPHONY_jll] 
[ALPS_jll] 
[BiCePS_jll] 
[CHIPPS_BLIS_jll] 
[MibS_jll]

2024-02-16 17:19 UTC, ViralBShah commented
I believe you have to merge CoinUtils first, and then use it in the other packages in the dependency chain - and keep doing that repeatedly.

2024-02-16 17:24 UTC, amontoison commented
Ipopt_jll is already linked with LBT so we could remove the folder for the artifact IpoptMKL_jll.

Yes, I discussed with Oscar a few days ago and we will start with CoinUtils, OsiUtils and Clp.

2024-02-16 17:25 UTC, ViralBShah commented
We can just let IpOptMKL be around, but just not update it going forward.

2024-02-16 21:47 UTC, odow commented
> I believe you have to merge CoinUtils first, and then use it in the other packages in the dependency chain - and keep doing that repeatedly.

Yeah, @amontoison has this under control, but they're traveling etc over the next few weeks. There is no rush.

2024-02-19 10:38 UTC, imciner2 commented
> Ipopt_jll is already linked with LBT so we could remove the folder for the artifact IpoptMKL_jll.

Has anyone tested running the LBT build with MKL selected? We should make sure we don't see the same problem that SLICOT had when using MKL with LBT (e.g. https://github.com/JuliaLinearAlgebra/MKL.jl/issues/138).

2024-02-20 08:51 UTC, imciner2 commented
> But we compile all COIN-OR packages with LP64 BLAS / LAPACK and not ILP64 BLAS / LAPACK so we can't have this problem.
> 
> I also checked with nm -D libCoinUtils.so.3.11.10 and only two symbols (related to dense LU) are used:

Excellent, then it should be safe to deprecate the old IpOptMKL and just use the main build from now on. IMO, I agree we can leave the build scripts there, but I think we should  add a `DEPRECATED` file to the folder explaining the deprecation and that the normal IpOpt should be used instead.

2024-05-31 22:35 UTC, ViralBShah commented
Should we merge this and then merge the Clp PR?

2024-06-04 03:56 UTC, odow commented
There's now 2.11.11 so we should probably first update to that 
https://github.com/coin-or/CoinUtils/releases/tag/releases%2F2.11.11

2024-06-04 05:01 UTC, amontoison commented
I will update the PR tomorrow. I forgot that I started to work on the LBT support in COIN-OR packages.

2024-06-20 02:59 UTC, odow commented on C/Coin-OR/coin-or-common.jl
> +CoinUtils_gitsha = "5b98c4bb87ceebedb86c6e921dc4ad0af6166c8e"
```suggestion
CoinUtils_gitsha = "15a819b7e8763b2557e4bf440f8cb62ee6734f36"
```

2024-06-20 02:59 UTC, odow commented on C/Coin-OR/coin-or-common.jl
> +CoinUtils_version = offset_version(v"2.11.10", v"0.0.0")
```suggestion
CoinUtils_version = offset_version(v"2.11.11", v"0.0.0")
```

2024-06-20 03:39 UTC, amontoison commented on C/Coin-OR/CoinUtils/build_tarballs.jl
> +# Last updated: 2024-02-05
```suggestion
# Last updated: 2024-06-19
```

2024-07-16 03:07 UTC, closed without merging