Reactant: bump version
JuliaPackaging/Yggdrasil pull request #9727
Opened 2024-11-03 07:07 UTC by Pangoraw

2024-11-03 09:06 UTC, mofeing commented
my bad, this is my fault

lemme fix this

2024-11-03 11:33 UTC, mofeing requested changes
this should fix it

2024-11-03 11:33 UTC, mofeing commented on R/Reactant/build_tarballs.jl
> +  GitSource(repo, "b08b9a2b2dea3a4f644c03ddc7fcb31fbc5ed2a8"),
```suggestion
  GitSource(repo, "e0873d0d2189e8ccf88ac5e62ee70dc594fa0d77"),
```

2024-11-04 08:02 UTC, Pangoraw commented
@mofeing I updated the commit again to include https://github.com/EnzymeAD/Reactant.jl/pull/221.

2024-11-04 08:09 UTC, mofeing commented
great! thanks @Pangoraw 

if all tests pass, it should be ready to go

2024-11-04 10:49 UTC, merged